server:
  port: 10000
spring:
  application:
    name: geteway
  cloud:
    nacos:
      discovery:
        #        server-addr: 192.168.43.228:8848
        server-addr: 192.168.31.122:8848 # nacos服务器地址
        namespace: c5a7e73a-3733-46fe-afb8-17497cdfade8
        cluster-name: cluster1
        ephemeral: true
    gateway:
      routes:
        - id: data-manager
          uri: lb://datamanager   # 负载均衡
          predicates: # 判断请求是否符合规则
            - Path=/dataManager/**

        - id: search-service
          uri: lb://searchservice
          predicates:
            - Path=/search/**
#          filters:
#            - StripPrefix=2
#      default-filters:
#        - AddRequestHeader=User, Tan
      globalcors: # 全局的跨域处理
        add-to-simple-url-handler-mapping: true # 解决options请求被拦截问题
        corsConfigurations:
          '[/**]':
            allowedOrigins: # 允许哪些网站的跨域请求
              - "http://127.0.0.1:8080"
            allowedMethods: # 允许的跨域ajax的请求方式
              - "GET"
              - "POST"
              - "DELETE"
              - "PUT"
              - "OPTIONS"
            allowedHeaders: "*" # 允许在请求中携带的头信息
            allowCredentials: true # 是否允许携带cookie
            maxAge: 360000 # 这次跨域检测的有效期